### ISSUE TITLE
Add garbage collector mechanism for unneeded resources

### ISSUE THREAD

**Issue by telpirion** [googleapis/nodejs-ai-platform#26]
Need to create a function, tool, or process that cleans up unneeded datasets, models, endpoints, training pipelines, batch predictions, model evaluations, etc.

When we run tests, sometimes the tests fail in a way that the `after` hooks aren't called. We need to ensure that all resources are destroyed when they aren't needed.

**Comment by bcoe** [comment]
Labeled this as a bug, as I consider leaking resources when tests fail a major issue (and I'd like this work to be captured by our SLOs).
