### ISSUE TITLE
Enhanced library: provide better mechanism for preserving manual edits

### ISSUE THREAD

**Issue by telpirion** [googleapis/nodejs-ai-platform#27]
The enhanced version of this library includes manual edits to the `src/index.ts` file that may be overwritten during generation. Right now, the `synth.py` file excludes this file from generation, which means that the index file might miss updates to the service.

We need to develop a way to:

1.  Generate a fresh version of the client library with updates to the service
2. Update the index.ts file as part of library generation
3. Preserve any manual edits to index.ts
4. Do all of the above without adding post-processing steps to synth.py

One suggestion is that we generate the library into a separate folder.

**Comment by bcoe** [comment]
@telpirion labeled as a feature request, which will not be captured by our current SLOs, but I think it's worthwhile to address this ASAP in the new year.

**Comment by matthewayne** [comment]
@bcoe is this still relevant since we've moved to owlbot.py in #99 ?

**Comment by bcoe** [comment]
@matthewayne yes, still relevant. There are manual changes that need to be made in `src/index.ts` whenever a new API client is added to the API.

To fix, you could add some sort of templatization logic perhaps, for generating these updates to the index files.

**Comment by meredithslota** [comment]
If this is still an issue, we should look into it — assigning to @dizcology to triage accordingly.

**Comment by telpirion** [comment]
Closing this for now to enable migration. This change may no longer be needed, given the library generation changes (i.e. Owlbot).
