### ISSUE TITLE
Receiving error `Error: 13 INTERNAL: Received RST_STREAM with code 0` with DatasetServiceClient methods

### ISSUE THREAD

**Issue by ivangabriele** [googleapis/nodejs-ai-platform#272]
#### Environment details

  - OS: Windows 11
  - Node.js version: 16.14.0
  - npm version:  8.3.1
  - `@google-cloud/aiplatform` version: 1.16.0

#### Steps to reproduce

Simply run this code :

```ts
import { DatasetServiceClient } from '@google-cloud/aiplatform'

const {
  GOOGLECLOUD_CLIENT_EMAIL,
  GOOGLECLOUD_CLIENT_PRIVATE_KEY,
  GOOGLECLOUD_LOCATION,
  GOOGLECLOUD_PROJECT_ID,
} = process.env

const datasetServiceClient = new DatasetServiceClient({
  credentials: {
    client_email: GOOGLECLOUD_CLIENT_EMAIL,
    private_key: GOOGLECLOUD_CLIENT_PRIVATE_KEY,
  },
  projectId: GOOGLECLOUD_PROJECT_ID,
})

const listDatasets = async () => {
  const parent = GOOGLECLOUD_LOCATION

  const request = {
    parent,
  }
  const [datasets] = await datasetServiceClient.listDatasets(request)

  console.log(datasets)
}

listDatasets()
```

#### Error output

```sh
$ yarn ts-node -r dotenv/config ./scripts/bug.ts
yarn run v1.22.17
$ C:\Users\ivang\Workspace\betagouv\metiers-numeriques\node_modules\.bin\ts-node -r dotenv/config ./scripts/bug.ts
C:\Users\ivang\Workspace\betagouv\metiers-numeriques\node_modules\@grpc\grpc-js\src\call.ts:81
  return Object.assign(new Error(message), status);
                       ^
Error: 13 INTERNAL: Received RST_STREAM with code 0
    at Object.callErrorFromStatus (C:\Users\ivang\Workspace\betagouv\metiers-numeriques\node_modules\@grpc\grpc-js\src\call.ts:81:24)
    at Object.onReceiveStatus (C:\Users\ivang\Workspace\betagouv\metiers-numeriques\node_modules\@grpc\grpc-js\src\client.ts:343:36)
    at Object.onReceiveStatus (C:\Users\ivang\Workspace\betagouv\metiers-numeriques\node_modules\@grpc\grpc-js\src\client-interceptors.ts:462:34)
    at Object.onReceiveStatus (C:\Users\ivang\Workspace\betagouv\metiers-numeriques\node_modules\@grpc\grpc-js\src\client-interceptors.ts:424:48)
    at C:\Users\ivang\Workspace\betagouv\metiers-numeriques\node_modules\@grpc\grpc-js\src\call-stream.ts:323:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 13,
  details: 'Received RST_STREAM with code 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Additional information

I tried to run an almost-exact copy of the [create-dataset.js example](https://github.com/googleapis/nodejs-ai-platform/blob/main/samples/create-dataset.js) and got the same error.

I tried to run it with pure JS in case it was related to `ts-node` but I also got the same error.

I tried to run it both under Git Bash and Powershell.

I checked an [opened issue](https://github.com/grpc/grpc-node/issues/1532) on `@grpc\grpc-js` repo but I don't think it's a bug related to their library from what I understood.

**Comment by Amoodaa** [comment]
Any progress on this?

**Comment by telpirion** [comment]
Thank you for logging this issue. I recommend trying without passing credentials explicitly--you should be able to use [Application Default Credentials](https://cloud.google.com/docs/authentication#adc) instead.

If you continue to see this problem, please open a new issue in one of these two repos:

+ [Samples](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/ai-platform/snippets)
+ [Client library](https://github.com/googleapis/google-cloud-node/tree/main/packages)
