### ISSUE TITLE
Enhanced library: refactor or remove value-converter.ts

### ISSUE THREAD

**Issue by telpirion** [googleapis/nodejs-ai-platform#28]
Waiting on [this PR in protobuf.js](https://github.com/protobufjs/protobuf.js/pull/1495).

The `src/value-converter.ts` allows conversion between Message and Value objects. When the above-mentioned PR is submitted, we will use protobuf.js instead for this conversion. At that time, the `value-converter.ts` file will be deleted and all the conversion logic will be contained in `src/helpers.ts`.

**Comment by alexander-fenster** [comment]
Since we first discussed this problem, I published an [npm package](https://github.com/googleapis/proto3-json-serializer-nodejs) for exactly this purpose. Can we start using it here?

**Comment by rosiezou** [comment]
Closing this issue because it is no longer applicable, given that JSON serialization/deserialization is now implemented in a separate package: https://www.npmjs.com/package/proto3-json-serializer.
